name: 'google_ads_source'
version: '0.3.1'
config-version: 2
require-dbt-version: [">=0.20.0"]
vars:
  google_ads_source:
    google_ads__final_url_performance: "{{ source('adwords','final_url_performance') }}"
    google_ads__click_performance: "{{ source('adwords','click_performance') }}"
    google_ads__criteria_performance: "{{ source('adwords','criteria_performance') }}"
  google_ads__url_passthrough_metrics: []
  google_ads__criteria_passthrough_metrics: []

models:
  google_ads_source:
    +schema: stg_google_ads
    +materialized: table
    tmp:
      +materialized: view


