name: 'google_ads_source_source_integration_tests'
version: '1.0.0'
profile: 'integration_tests'
config-version: 2

vars:
  google_ads__final_url_performance: "{{ ref('google_ads_final_url_performance_data') }}"
  google_ads__click_performance: "{{ ref('google_ads_click_performance_data') }}"
  google_ads__criteria_performance: "{{ ref('google_ads_criteria_performance_data') }}"